// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqarrpymjodhzbifssuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxYXJycHltam9kaHpiaWZzc3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjA1MzYsImV4cCI6MjA3MjgzNjUzNn0.1OvrKlQ3gIPkYNtOIRyaHUm_OBJXbbbmG7R2yL2RMaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});